### ndarray 정렬

In [3]:
import numpy as np

##### 1차원 배열 정렬

In [116]:
arr = np.random.randint(1, 11, 10)
arr

array([2, 8, 7, 9, 4, 2, 3, 8, 4, 6])

In [138]:
# np.sort(arr) : 정렬된 ndarray를 반환
print(np.sort(arr))
print(arr)
print(np.sort(arr)[::-1])

[2 2 3 4 4 6 7 8 8 9]
[2 8 7 9 4 2 3 8 4 6]
[9 8 8 7 6 4 4 3 2 2]


---

##### 2차원 배열 정렬

In [152]:
arr = np.random.randint(10, size=(3,4)) # 0잇강 10 미만
arr

array([[7, 4, 4, 9],
       [8, 7, 5, 0],
       [5, 3, 7, 2]])

In [153]:
np.sort(arr) # 기본값 axis=1

array([[4, 4, 7, 9],
       [0, 5, 7, 8],
       [2, 3, 5, 7]])

In [154]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[5 3 4 0]
 [7 4 5 2]
 [8 7 7 9]]
[[4 4 7 9]
 [0 5 7 8]
 [2 3 5 7]]


In [156]:
print(np.sort(arr, axis=None)) # axis = None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 2 3 4 4 5 5 7 7 7 8 9]
(12,)


##### np.argsort
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [158]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [173]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

print(np.sort(album_sales)[::-1])
print(np.argsort(album_sales)[::-1])

sales_desc = np.argsort(album_sales)[::-1]
print(names[sales_desc])

[1000  900  870  670]
[2 0 1 3]
['제니' '리사' '로제' '지수']


In [175]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 2, 28], [17, 18, 30]])

print(np.argsort(arr))
print(np.argsort(arr, axis=1)) # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0)) # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[1 2 0]
 [0 1 2]]
[[1 2 0]
 [0 1 2]]
[[1 0 0]
 [0 1 1]]
