### ndarray 형태 변경

In [1]:
import numpy as np

In [11]:
# reshape()
# 요소의 갯수가 맞는 shape으로 변형 가능
arr = np.arange(12)
print(arr.ndim, arr)

arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
arr = arr.reshape(1, 12)
print(arr.ndim, arr.shape)
print(arr)

arr = arr.reshape(2, 2, 3)
#arr = arr.reshape(2, 2, 2)
print(arr.ndim, arr.shape)
print(arr)

1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
2 (1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [10]:
# reshape() -> -1
arr = arr.reshape(-1)   # 1차원 처리 
print(arr)

# -1인 축은 자동으로 계산
arr = arr.reshape(4, -1) 
arr = arr.reshape(-1, 4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
# np.ravel() : 1차원 변환
arr = np.arange(50).reshape(5, 10)
print(arr)
print(np.ravel(arr))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [17]:
# np.expand_dims() : 차원 추가
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)
print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [24]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape, arr_2d)
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=0).shape)
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=1).shape)
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=2).shape)

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [30]:
# np.squeeze() : 차원의 값이 1일 때 제거 
arr = np.array([[1,2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0)
arr2 = np.squeeze(arr, axis=1)
print(arr2.shape)

(1, 2)


ValueError: cannot select an axis to squeeze out which has size not equal to one