In [166]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.font_manager as fm
import matplotlib
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

font_path = '/Users/hwangjunho/Desktop/encore_skn11/04_data-analysis/03_matplotlib/AppleSDGothicNeo.ttc'
font = fm.FontProperties(fname=font_path).get_name()
matplotlib.rc('font', family=font)

In [167]:
iris_data = load_iris()
iris_data.keys()
iris_data.target_names
iris_data.feature_names 

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [168]:
print(iris_data.data)   # input 데이터 (특성 데이터)
print(iris_data.feature_names)
len(iris_data.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [169]:
print(iris_data.target)     # 숫자로 인코딩된 라벨 데이터 (정답 데이터)
print(iris_data.target_names)   # 라벨 데이터의 이름
len(iris_data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


150

In [170]:
# 데이터 전처리
# 1. 입력-라벨 데이터
# 2. 학습용-테스트용 데이터
# 3. 데이터 정규화
iris_input = iris_data.data
iris_label = iris_data.target
train_input, test_input, train_label, test_label = train_test_split(iris_input, iris_label, test_size=0.3, stratify=iris_label, random_state=55)

train_input, test_input, train_label, test_label
print(len(train_input), len(test_input))
print(len(train_label), len(test_label))
 
mean = np.mean(train_input, axis=0)
std = np.std(train_input, axis=0)
print(mean, std)

train_scaled = (train_input - mean) / std
test_scaled= (test_input - mean) / std
print(train_scaled, test_scaled)

105 45
105 45
[5.81333333 3.07714286 3.72952381 1.20761905] [0.7432319  0.43823393 1.71879935 0.74880161]
[[-0.95977223 -1.31697437 -0.42443803 -0.14372171]
 [ 1.32753542 -0.17603123  1.03006566  1.1917455 ]
 [ 1.19298791 -0.17603123  0.73916492  0.65755862]
 [ 2.538463   -0.63240848  1.72822744  1.05819878]
 [-1.09431974  0.96491191 -1.41350054 -1.21209548]
 [-1.09431974  1.19310054 -1.35532039 -1.3456422 ]
 [-0.95977223  0.96491191 -1.35532039 -1.3456422 ]
 [-1.22886725  0.0521574  -1.29714025 -1.47918892]
 [ 0.78934538 -0.63240848  1.08824581  1.1917455 ]
 [ 0.92389289 -0.17603123  1.20460611  1.32529222]
 [ 0.65479788  0.50853466  1.3209664   1.72593238]
 [-0.15248718  1.6494778  -1.18077995 -1.21209548]
 [-0.5561297  -0.17603123  0.44826419  0.39046517]
 [ 0.65479788 -0.63240848  0.79734507  0.39046517]
 [ 0.11660784 -0.17603123  0.27372374  0.39046517]
 [-0.82522472  2.33404369 -1.29714025 -1.47918892]
 [-0.28703469 -0.40421986 -0.07535714  0.12337173]
 [-1.63250977  0.73672329 -

In [171]:
# 훈현 
kn = KNeighborsClassifier()
kn.fit(train_scaled, train_label)

KNeighborsClassifier()

In [172]:
# 평가 score
kn.score(test_scaled, test_label)

1.0