In [180]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.font_manager as fm
import matplotlib
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

font_path = '/Users/hwangjunho/Desktop/encore_skn11/04_data-analysis/03_matplotlib/AppleSDGothicNeo.ttc'
font = fm.FontProperties(fname=font_path).get_name()
matplotlib.rc('font', family=font)

In [181]:
iris_data = load_iris()
iris_data.keys()
iris_data.target_names
iris_data.feature_names 

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [182]:
print(iris_data.data)   # input 데이터 (특성 데이터)
print(iris_data.feature_names)
len(iris_data.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [183]:
print(iris_data.target)     # 숫자로 인코딩된 라벨 데이터 (정답 데이터)
print(iris_data.target_names)   # 라벨 데이터의 이름
len(iris_data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


150

In [184]:
# 데이터 전처리
# 1. 입력-라벨 데이터
# 2. 학습용-테스트용 데이터
# 3. 데이터 정규화
iris_input = iris_data.data
iris_label = iris_data.target
train_input, test_input, train_label, test_label = train_test_split(iris_input, iris_label, test_size=0.3, stratify=iris_label, random_state=10)

train_input, test_input, train_label, test_label
print(len(train_input), len(test_input))
print(len(train_label), len(test_label))
 
mean = np.mean(train_input, axis=0)
std = np.std(train_input, axis=0)
print(mean, std)

train_scaled = (train_input - mean) / std
test_scaled= (test_input - mean) / std
print(train_scaled, test_scaled)

105 45
105 45
[5.85619048 3.04952381 3.77904762 1.20095238] [0.83185665 0.43558911 1.76816802 0.75900878]
[[-1.02925243e+00  1.26375105e+00 -1.34548730e+00 -1.31876258e+00]
 [-6.75482682e-02 -8.02416326e-01  1.81516902e-01 -2.64756332e-01]
 [-9.09039407e-01  1.03417690e+00 -1.34548730e+00 -1.18701180e+00]
 [ 5.33516831e-01 -1.72071294e+00  3.51184036e-01  1.30496012e-01]
 [ 1.72877771e-01 -3.43268020e-01  4.07739747e-01  3.93997574e-01]
 [ 1.72877771e-01  8.04602747e-01  4.07739747e-01  5.25748356e-01]
 [ 8.94155890e-01 -1.13693866e-01  3.51184036e-01  2.62246793e-01]
 [ 1.01436891e+00 -1.13693866e-01  8.03629727e-01  1.44800382e+00]
 [-1.87761288e-01 -1.03199048e+00 -1.57817366e-01 -2.64756332e-01]
 [-1.26967847e+00 -1.13693866e-01 -1.34548730e+00 -1.45051336e+00]
 [-1.26967847e+00 -1.13693866e-01 -1.34548730e+00 -1.18701180e+00]
 [ 1.72877771e-01 -1.95028709e+00  6.90518304e-01  3.93997574e-01]
 [ 6.53729850e-01 -8.02416326e-01  8.60185438e-01  9.21000699e-01]
 [ 6.53729850e-01  3.45

In [185]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_input)
train_scaled = scaler.transform(train_input)
test_scaled = scaler.transform(test_input)

In [186]:
# 훈현 
kn = KNeighborsClassifier()
kn.fit(train_scaled, train_label)

KNeighborsClassifier()

In [187]:
# 평가 score
kn.score(test_scaled, test_label)

1.0

In [188]:
# 평가 : accuracy_score
from sklearn.metrics import accuracy_score
pred = kn.predict(test_scaled)
accuracy_score(test_label, pred)

1.0