## Numpy: basic

In [1]:
import numpy as np

### [실습] 다양한 방법으로 배열 생성
NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [26]:
arr = np.zeros((4,3))
print('#1')
print(arr)
print('\n')

arr = np.ones((3,3))
print('#2')
print(arr)
print('\n')

arr = np.arange(0, 21, 5)
print('#3')
print(arr)
print('\n')

arr = np.linspace(0, 1, 4)
print('#4')
print(arr)
print('\n')

arr = np.random.randn(2, 2)
print('#5')
print(arr)

arr = np.random.normal(loc = 0, scale=1, size=(2, 2))
print(arr)

#1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#3
[ 0  5 10 15 20]


#4
[0.         0.33333333 0.66666667 1.        ]


#5
[[-0.81313574  0.25956017]
 [-0.76649316 -0.25056373]]
[[-0.11839564  0.47226981]
 [ 0.04667196  1.03079751]]


---

### [실습 1] 인덱싱과 슬라이싱

아래 배열에서 인덱싱과 슬라이싱을 사용하여 다음 작업을 수행하세요.

1. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
2. 배열 `arr`에서 1번째 열만 추출
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

In [35]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(f'#1 {arr[1, 2]}')
print(f'#2 {arr[:, 0]}')
print(f'#3 {arr[0:2, 0:2]}')

#1 60
#2 [10 40 70]
#3 [[10 20]
 [40 50]]


### [실습 2] 팬시 인덱싱과 불리언 인덱싱
아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [23]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(f'#1 {arr[0:5:2]}')
print(f'#2 {arr[arr>50]}')



#1 [10 30 50]
#2 [60 70]


### [실습 3] 제품 판매 데이터 분석
어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [64]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(f'#1 {sales[sales>200]}')
print(f'#2 {sales[sales[:,2] <= 100, 0:2]}')
print(f'#2 {sales[sales[:,1] >= 150]}')



#1 [220 300 320 310]
#2 [[120 150]
 [ 50  45]]
#2 [[120 150 100]
 [200 180 220]
 [300 320 310]]
