## Numpy: 병합

In [3]:
import numpy as np

### [실습 1] 1차원 배열 병합

다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


### [실습 2] 2차원 배열 병합

다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
